### ISSUE TITLE
Estimación de tiempo, costo y esfuerzo

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode#11]
Tiempo: 8 horas.
Fecha Límite: 16 de Abril.
Descripción: Realizar la estimación de tiempo, costo y esfuerzo en una herramienta web de gestión de software.

**Comment by ingalexis** [comment]
https://yourcodes.aceproject.com/ 
Se utilizo ace project como herramienta de estimacion de tiempo, costo y esfuerzo.
