### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode#3]
Tiempo: 4 horas.
Fecha Límite: 13 de Abril.
Descripción: Realizar el diagrama de casos de uso sobre los requerimientos funcionales de la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
![casos_de_usos](https://cloud.githubusercontent.com/assets/25873547/25031433/79f2f9e4-2092-11e7-88f6-dd58893e1775.PNG)

**Comment by MauricioCaviedes21** [comment]
Diagrama de Casos de Usos versión 2.

![casos_de_usos](https://cloud.githubusercontent.com/assets/25873547/25047846/d4402522-20fe-11e7-902b-ed7f29367ba9.PNG)

**Comment by MauricioCaviedes21** [comment]
Diagrama de casos de usos versión 2

![casos_de_usos](https://cloud.githubusercontent.com/assets/25873547/25049043/558f6d12-2105-11e7-9bf2-051744634137.PNG)
