### ISSUE TITLE
Requerimientos no funcionales

### ISSUE THREAD

**Issue by fabiiancano** [YourCodeUnillanos/YourCode#6]
Tiempo: 3 horas.
Fecha Límite: 13 de Abril.
Descripción: Escribir y detallar los requerimientos no funcionales que tendrá la aplicación YourCode.

**Comment by MauricioCaviedes21** [comment]
[Requerimientos funcionales y No funcionales.pdf](https://github.com/YourCodeUnillanos/YourCode/files/922530/Requerimientos.funcionales.y.No.funcionales.pdf)
